const products = [
	{
		name: "Laptop Nova X1",
		brand: "TechNova",
		description:
			"Ultrabook leggero con prestazioni elevate per professionisti in movimento",
		specs: "Intel Core i7, 16GB RAM, 512GB SSD, 14'' FHD, Wi-Fi 6",
		price: 1099.99,
		stock_quantity: 25,
		image_url: "laptop-icon-1.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Titan Pro",
		brand: "IronWare",
		description:
			"Potenza desktop in formato portatile, ideale per gaming e rendering",
		specs: "AMD Ryzen 9, 32GB RAM, 1TB SSD, RTX 4070, 17'' QHD",
		price: 1899.0,
		stock_quantity: 12,
		image_url: "laptop-icon-2.jpg",
		category_id: 1,
	},
	{
		name: "Laptop EcoLite 13",
		brand: "GreenByte",
		description:
			"Design minimal e consumi ridotti, perfetto per studenti e smart working",
		specs: "Intel Core i3, 8GB RAM, 256GB SSD, 13'' HD",
		price: 499.9,
		stock_quantity: 40,
		image_url: "laptop-icon-3.jpg",
		category_id: 1,
	},
	{
		name: "Laptop CreatorBook",
		brand: "PixelForge",
		description: "Pensato per creativi: schermo ad alta fedeltà e GPU dedicata",
		specs: "Intel Core i7, 16GB RAM, 1TB SSD, RTX 3050, 15.6'' 4K OLED",
		price: 1499.0,
		stock_quantity: 18,
		image_url: "laptop-icon-4.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Flex360",
		brand: "MobilityX",
		description: "Convertibile 2-in-1 con touchscreen e penna inclusa",
		specs: "Intel Core i5, 8GB RAM, 512GB SSD, 14'' FHD Touch",
		price: 899.0,
		stock_quantity: 30,
		image_url: "laptop-icon-5.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Stealth Air",
		brand: "SilentTech",
		description:
			"Sottile e silenzioso, con raffreddamento passivo e autonomia estesa",
		specs: "Intel Core M, 8GB RAM, 256GB SSD, 13'' FHD",
		price: 649.0,
		stock_quantity: 22,
		image_url: "laptop-icon-6.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Quantum Edge",
		brand: "CoreLogic",
		description: "Prestazioni bilanciate per lavoro e intrattenimento",
		specs: "AMD Ryzen 5, 16GB RAM, 512GB SSD, 15.6'' FHD",
		price: 799.0,
		stock_quantity: 35,
		image_url: "laptop-icon-7.jpg",
		category_id: 1,
	},
	{
		name: "Laptop UrbanGo",
		brand: "CityTech",
		description: "Compatto e resistente, ideale per la mobilità urbana",
		specs: "Intel Core i5, 8GB RAM, 256GB SSD, 12.5'' HD",
		price: 599.0,
		stock_quantity: 28,
		image_url: "laptop-icon-8.jpg",
		category_id: 1,
	},
	{
		name: "Laptop VisionBook",
		brand: "ConnectPro",
		description: "Ottimizzato per videoconferenze e collaborazione remota",
		specs: "Intel Core i5, 16GB RAM, 512GB SSD, Webcam HD, 15'' FHD",
		price: 849.0,
		stock_quantity: 20,
		image_url: "laptop-icon-9.jpg",
		category_id: 1,
	},
	{
		name: "Laptop ZenStation",
		brand: "ZenCore",
		description: "Esperienza fluida e silenziosa per ambienti professionali",
		specs: "AMD Ryzen 7, 16GB RAM, 1TB SSD, 15.6'' QHD",
		price: 1199.0,
		stock_quantity: 15,
		image_url: "laptop-icon-10.jpg",
		category_id: 1,
	},
	{
		name: "iPhone 15 Pro",
		brand: "Apple",
		description: "Smartphone con chip A17 Pro e fotocamera avanzata.",
		specs: "Display 6.1'', 256GB, 8GB RAM, iOS 17",
		price: 1299,
		stock_quantity: 25,
		image_url: "phone-icon-1.jpg",
		category_id: 2,
	},
	{
		name: "Galaxy S23 Ultra",
		brand: "Samsung",
		description: "Top di gamma con fotocamera da 200MP e S-Pen.",
		specs: "Display 6.8'', 512GB, 12GB RAM, Android 13",
		price: 1399,
		stock_quantity: 18,
		image_url: "phone-icon-2.jpg",
		category_id: 2,
	},
	{
		name: "Pixel 8 Pro",
		brand: "Google",
		description: "Smartphone con intelligenza artificiale avanzata.",
		specs: "Display 6.7'', 256GB, 12GB RAM, Android 14",
		price: 1099,
		stock_quantity: 30,
		image_url: "phone-icon-3.jpg",
		category_id: 2,
	},
	{
		name: "Xiaomi 13 Pro",
		brand: "Xiaomi",
		description: "Prestazioni elevate e fotocamera Leica.",
		specs: "Display 6.73'', 256GB, 12GB RAM, Android 13",
		price: 999,
		stock_quantity: 40,
		image_url: "phone-icon-4.jpg",
		category_id: 2,
	},
	{
		name: "OnePlus 11",
		brand: "OnePlus",
		description: "Smartphone veloce con ricarica rapida da 100W.",
		specs: "Display 6.7'', 256GB, 16GB RAM, Android 13",
		price: 849,
		stock_quantity: 35,
		image_url: "phone-icon-5.jpg",
		category_id: 2,
	},
	{
		name: "Sony Xperia 1 V",
		brand: "Sony",
		description: "Smartphone con display 4K e fotocamera professionale.",
		specs: "Display 6.5'' 4K OLED, 256GB, 12GB RAM, Android 13",
		price: 1199,
		stock_quantity: 15,
		image_url: "phone-icon-6.jpg",
		category_id: 2,
	},
	{
		name: "Motorola Edge 40 Pro",
		brand: "Motorola",
		description: "Smartphone potente con Snapdragon 8 Gen 2.",
		specs: "Display 6.67'', 256GB, 12GB RAM, Android 13",
		price: 799,
		stock_quantity: 28,
		image_url: "phone-icon-7.jpg",
		category_id: 2,
	},
	{
		name: "Huawei P60 Pro",
		brand: "Huawei",
		description: "Fotocamera XMAGE con prestazioni di fascia alta.",
		specs: "Display 6.67'', 256GB, 12GB RAM, HarmonyOS",
		price: 1099,
		stock_quantity: 20,
		image_url: "phone-icon-8.jpg",
		category_id: 2,
	},
	{
		name: "Realme GT Neo 5",
		brand: "Realme",
		description: "Smartphone gaming con ricarica ultra veloce da 240W.",
		specs: "Display 6.74'', 256GB, 16GB RAM, Android 13",
		price: 649,
		stock_quantity: 50,
		image_url: "phone-icon-9.jpg",
		category_id: 2,
	},
	{
		name: "Oppo Find X6 Pro",
		brand: "Oppo",
		description: "Top di gamma con fotocamera Hasselblad.",
		specs: "Display 6.82'', 512GB, 16GB RAM, Android 13",
		price: 1249,
		stock_quantity: 22,
		image_url: "phone-icon-10.jpg",
		category_id: 2,
	},
	{
		name: "VortexSound X7",
		brand: "VortexLab",
		description:
			"Cuffie da gaming con audio surround 7.1 e microfono removibile.",
		specs: "Driver 50mm, USB, LED RGB, cancellazione rumore",
		price: 129,
		stock_quantity: 18,
		image_url: "headCuff-1.jpg",
		category_id: 3,
	},
	{
		name: "NovaAudio Pro",
		brand: "NovaTech",
		description: "Headset wireless con bassi potenziati e comfort prolungato.",
		specs: "Bluetooth 5.2, autonomia 30h, padiglioni memory foam",
		price: 149,
		stock_quantity: 22,
		image_url: "headCuff-2.jpg",
		category_id: 3,
	},
	{
		name: "StealthCom S1",
		brand: "StealthTech",
		description: "Cuffie leggere e silenziose per ambienti professionali.",
		specs: "Jack 3.5mm, microfono direzionale, design minimal",
		price: 69,
		stock_quantity: 30,
		image_url: "headCuff-3.jpg",
		category_id: 3,
	},
	{
		name: "TitanVoice G5",
		brand: "IronWare",
		description: "Headset da competizione con isolamento acustico avanzato.",
		specs: "USB, driver 53mm, microfono con filtro pop",
		price: 159,
		stock_quantity: 12,
		image_url: "headCuff-4.jpg",
		category_id: 3,
	},
	{
		name: "EcoSound Lite",
		brand: "GreenByte",
		description: "Cuffie sostenibili con materiali riciclati e packaging eco.",
		specs: "Jack 3.5mm, driver 40mm, compatibili con tutti i dispositivi",
		price: 39,
		stock_quantity: 40,
		image_url: "headCuff-5.jpgg",
		category_id: 3,
	},
	{
		name: "BlitzTalk Z1",
		brand: "BlitzGear",
		description: "Headset compatto per gamer in mobilità.",
		specs: "Bluetooth, microfono integrato, autonomia 20h",
		price: 89,
		stock_quantity: 25,
		image_url: "headCuff-6.jpg",
		category_id: 3,
	},
	{
		name: "HyperWave Edge",
		brand: "HyperZone",
		description: "Cuffie RGB con profili audio personalizzabili.",
		specs: "USB, software dedicato, microfono retrattile",
		price: 119,
		stock_quantity: 16,
		image_url: "headCuff-7.jpg",
		category_id: 3,
	},
	{
		name: "OmegaSound Prime",
		brand: "OmegaPlay",
		description: "Headset premium con audio Hi-Fi e struttura in alluminio.",
		specs: "USB-C, driver 60mm, microfono staccabile",
		price: 179,
		stock_quantity: 10,
		image_url: "headCuff-8.jpg",
		category_id: 3,
	},
	{
		name: "CityVoice Urban",
		brand: "CityTech",
		description: "Cuffie wireless per lavoro remoto e videoconferenze.",
		specs: "Bluetooth, microfono ambientale, autonomia 25h",
		price: 99,
		stock_quantity: 28,
		image_url: "headCuff-9.jpg",
		category_id: 3,
	},
	{
		name: "ShadowCom Elite",
		brand: "DarkCore",
		description:
			"Headset da gioco con illuminazione interna e audio direzionale.",
		specs: "Surround 7.1, USB, microfono noise-cancelling",
		price: 139,
		stock_quantity: 14,
		image_url: "headCuff-10.jpg",
		category_id: 3,
	},
	{
		name: "Secretlab Titan Evo 2023",
		brand: "Secretlab",
		description:
			"Sedia da gaming ergonomica con memory foam e supporto lombare regolabile.",
		specs:
			"Materiale: pelle sintetica, braccioli 4D, schienale reclinabile 165°",
		price: 549,
		stock_quantity: 20,
		image_url: "chairs-1.jpg",
		category_id: 4,
	},
	{
		name: "DXRacer Formula Series",
		brand: "DXRacer",
		description:
			"Classica sedia da gaming con design racing e cuscini inclusi.",
		specs: "Materiale: tessuto, supporto fino a 120kg, reclinazione 135°",
		price: 329,
		stock_quantity: 35,
		image_url: "chairs-2.jpg",
		category_id: 4,
	},
	{
		name: "Razer Iskur",
		brand: "Razer",
		description: "Sedia premium con supporto lombare ergonomico regolabile.",
		specs: "Materiale: similpelle, braccioli 4D, schienale reclinabile 139°",
		price: 499,
		stock_quantity: 18,
		image_url: "chairs-3.jpg",
		category_id: 4,
	},
	{
		name: "Corsair T3 Rush",
		brand: "Corsair",
		description: "Sedia in tessuto traspirante ispirata al mondo racing.",
		specs: "Materiale: tessuto morbido, braccioli 4D, reclinazione 180°",
		price: 299,
		stock_quantity: 40,
		image_url: "chairs-4.jpg",
		category_id: 4,
	},
	{
		name: "AKRacing Masters Series Pro",
		brand: "AKRacing",
		description: "Sedia extra large progettata per lunghe sessioni di gioco.",
		specs: "Materiale: pelle PU, supporto fino a 150kg, reclinazione 180°",
		price: 599,
		stock_quantity: 12,
		image_url: "chairs-5.jpg",
		category_id: 4,
	},
	{
		name: "Vertagear SL5000",
		brand: "Vertagear",
		description: "Design racing con cuscini lombari e cervicali inclusi.",
		specs:
			"Materiale: pelle sintetica, braccioli regolabili, reclinazione 170°",
		price: 399,
		stock_quantity: 28,
		image_url: "chairs-6.jpg",
		category_id: 4,
	},
	{
		name: "Noblechairs Hero",
		brand: "Noblechairs",
		description:
			"Sedia elegante con supporto lombare integrato e materiali premium.",
		specs: "Materiale: similpelle, braccioli 4D, reclinazione 135°",
		price: 469,
		stock_quantity: 22,
		image_url: "chairs-7.jpg",
		category_id: 4,
	},
	{
		name: "AndaSeat Kaiser 3",
		brand: "AndaSeat",
		description:
			"Ampia sedia da gaming con magneti per poggiatesta e braccioli.",
		specs: "Materiale: pelle PU, braccioli magnetici, reclinazione 165°",
		price: 549,
		stock_quantity: 15,
		image_url: "chairs-8.jpg",
		category_id: 4,
	},
	{
		name: "Cougar Argo",
		brand: "Cougar",
		description:
			"Sedia da gaming ibrida con struttura in alluminio e design ergonomico.",
		specs:
			"Materiale: mesh traspirante, regolazione completa, supporto lombare",
		price: 649,
		stock_quantity: 10,
		image_url: "chairs-9.jpg",
		category_id: 4,
	},
	{
		name: "ThunderX3 TC5",
		brand: "ThunderX3",
		description: "Sedia da gaming dal design sportivo con comfort elevato.",
		specs: "Materiale: pelle PU, braccioli 3D, reclinazione 180°",
		price: 259,
		stock_quantity: 50,
		image_url: "chairs-10.jpg",
		category_id: 4,
	},
	{
		name: "X-Racer GT Pro",
		brand: "GameForge",
		description: "Scrivania da gaming con LED RGB e supporto cuffie.",
		specs: "140x60cm, struttura in acciaio, superficie in fibra di carbonio",
		price: 299,
		stock_quantity: 15,
		image_url: "desk-1.jpg",
		category_id: 5,
	},
	{
		name: "ShadowDesk Elite",
		brand: "DarkCore",
		description:
			"Tavolo regolabile elettricamente con gestione cavi integrata.",
		specs: "160x70cm, altezza regolabile, porta USB",
		price: 499,
		stock_quantity: 10,
		image_url: "desk-2.jpg",
		category_id: 5,
	},
	{
		name: "Nebula Station",
		brand: "NebulaGear",
		description:
			"Design futuristico con illuminazione ambientale e supporto monitor.",
		specs: "150x65cm, LED RGB, supporto doppio monitor",
		price: 389,
		stock_quantity: 20,
		image_url: "desk-3.jpg",
		category_id: 5,
	},
	{
		name: "Titan Arena",
		brand: "IronPlay",
		description: "Scrivania robusta per setup multi-schermo e accessori.",
		specs: "180x75cm, struttura rinforzata, 3 livelli",
		price: 549,
		stock_quantity: 8,
		image_url: "desk-4.jpg",
		category_id: 5,
	},
	{
		name: "Stealth Command",
		brand: "StealthTech",
		description: "Tavolo minimal con finitura opaca e supporto controller.",
		specs: "130x60cm, superficie antiscivolo, porta controller",
		price: 259,
		stock_quantity: 25,
		image_url: "desk-5.jpg",
		category_id: 5,
	},
	{
		name: "Vortex Edge",
		brand: "VortexLab",
		description: "Scrivania angolare per massima immersione nel gioco.",
		specs: "L-shape, LED RGB, supporto PC tower",
		price: 479,
		stock_quantity: 12,
		image_url: "desk-6.jpg",
		category_id: 5,
	},
	{
		name: "HyperDesk Z1",
		brand: "HyperZone",
		description: "Tavolo compatto per gamer con spazio ottimizzato.",
		specs: "120x55cm, porta bicchiere, tappetino integrato",
		price: 219,
		stock_quantity: 30,
		image_url: "desk-7.jpg",
		category_id: 5,
	},
	{
		name: "Omega Core",
		brand: "OmegaPlay",
		description: "Scrivania premium con finiture in alluminio e LED dinamici.",
		specs: "150x70cm, LED dinamici, porta accessori magnetici",
		price: 599,
		stock_quantity: 6,
		image_url: "desk-8.jpg",
		category_id: 5,
	},
	{
		name: "BlitzStation",
		brand: "BlitzGear",
		description: "Setup modulare per gamer professionisti.",
		specs: "Modulare, supporto monitor, gestione termica",
		price: 429,
		stock_quantity: 18,
		image_url: "desk-9.jpg",
		category_id: 5,
	},
	{
		name: "NovaDesk Prime",
		brand: "NovaTech",
		description: "Scrivania ergonomica con pannello touch e speaker Bluetooth.",
		specs: "160x70cm, pannello touch, speaker integrati",
		price: 649,
		stock_quantity: 5,
		image_url: "desk-10.jpg",
		category_id: 5,
	},
	{
		name: "PowerStation Z900",
		brand: "CoreLogic",
		description:
			"Desktop ad alte prestazioni per multitasking e sviluppo software.",
		specs: "Intel Core i9, 32GB RAM, 1TB SSD, RTX 4060, Windows 11 Pro",
		price: 1799,
		stock_quantity: 10,
		image_url: "pc-1.jpg",
		category_id: 6,
	},
	{
		name: "SilentBox S5",
		brand: "SilentTech",
		description:
			"PC ultra silenzioso con raffreddamento passivo e case compatto.",
		specs: "AMD Ryzen 5, 16GB RAM, 512GB SSD, Radeon Vega, Windows 11",
		price: 899,
		stock_quantity: 18,
		image_url: "pc-2.jpg",
		category_id: 6,
	},
	{
		name: "NovaCube X",
		brand: "NovaTech",
		description: "Mini PC potente per ufficio e intrattenimento domestico.",
		specs: "Intel Core i5, 16GB RAM, 512GB SSD, Wi-Fi 6, Windows 11",
		price: 749,
		stock_quantity: 25,
		image_url: "pc-3.jpg",
		category_id: 6,
	},
	{
		name: "TitanForge G1",
		brand: "IronWare",
		description: "Workstation per grafica 3D e rendering professionale.",
		specs: "AMD Ryzen 9, 64GB RAM, 2TB SSD, RTX 4080, Windows 11 Pro",
		price: 2899,
		stock_quantity: 6,
		image_url: "pc-4.jpg",
		category_id: 6,
	},
	{
		name: "BlitzCore M7",
		brand: "BlitzGear",
		description:
			"Desktop modulare per upgrade rapidi e configurazioni personalizzate.",
		specs: "Intel Core i7, 32GB RAM, 1TB SSD, RTX 3070, Windows 11",
		price: 1599,
		stock_quantity: 14,
		image_url: "pc-5.jpg",
		category_id: 6,
	},
	{
		name: "VortexStation V5",
		brand: "VortexLab",
		description: "PC da gaming con illuminazione RGB e raffreddamento liquido.",
		specs: "Intel Core i9, 32GB RAM, 1TB SSD + 2TB HDD, RTX 4090, Windows 11",
		price: 3299,
		stock_quantity: 5,
		image_url: "pc-6.jpg",
		category_id: 6,
	},
	{
		name: "EcoBox E3",
		brand: "GreenByte",
		description:
			"Desktop eco-friendly con materiali riciclati e basso consumo.",
		specs: "Intel Core i3, 8GB RAM, 256GB SSD, Intel UHD, Windows 11",
		price: 499,
		stock_quantity: 30,
		image_url: "pc-7.jpg",
		category_id: 6,
	},
	{
		name: "StealthRig SR1",
		brand: "StealthTech",
		description: "PC nero opaco con design minimal e prestazioni fluide.",
		specs: "AMD Ryzen 7, 16GB RAM, 1TB SSD, Radeon RX 6700 XT, Windows 11",
		price: 1299,
		stock_quantity: 20,
		image_url: "pc-8.jpg",
		category_id: 6,
	},
	{
		name: "HyperCore H10",
		brand: "HyperZone",
		description: "Desktop per streaming e editing video in tempo reale.",
		specs: "Intel Core i7, 32GB RAM, 1TB SSD, RTX 3060 Ti, Windows 11",
		price: 1499,
		stock_quantity: 12,
		image_url: "pc-9.jpg",
		category_id: 6,
	},
	{
		name: "OmegaBox Ultra",
		brand: "OmegaPlay",
		description: "PC da competizione per eSports e simulazioni avanzate.",
		specs: "AMD Ryzen 9, 64GB RAM, 2TB SSD, RTX 4080 Ti, Windows 11 Pro",
		price: 2599,
		stock_quantity: 7,
		image_url: "pc-10.jpg",
		category_id: 6,
	},
	{
		name: "ViperX Precision",
		brand: "CoreLogic",
		description:
			"Mouse da gaming ultra preciso con sensore ottico da 26.000 DPI.",
		specs: "RGB, 8 pulsanti programmabili, USB-C",
		price: 89,
		stock_quantity: 20,
		image_url: "mouse-1.jpg",
		category_id: 7,
	},
	{
		name: "StealthMouse S1",
		brand: "StealthTech",
		description: "Mouse wireless silenzioso per ambienti professionali.",
		specs: "Bluetooth 5.1, batteria 60 giorni, sensore laser",
		price: 49,
		stock_quantity: 35,
		image_url: "mouse-2.jpg",
		category_id: 7,
	},
	{
		name: "NovaClick Elite",
		brand: "NovaTech",
		description: "Mouse ergonomico con supporto palmare e scroll fluido.",
		specs: "USB, 6 pulsanti, DPI regolabile",
		price: 39,
		stock_quantity: 40,
		image_url: "mouse-3.jpg",
		category_id: 7,
	},
	{
		name: "ShadowGrip Pro",
		brand: "DarkCore",
		description: "Mouse da gioco con impugnatura antiscivolo e LED dinamici.",
		specs: "RGB, 12 pulsanti, DPI 18.000",
		price: 69,
		stock_quantity: 18,
		image_url: "mouse-4.jpg",
		category_id: 7,
	},
	{
		name: "EcoMouse Lite",
		brand: "GreenByte",
		description: "Mouse sostenibile con materiali riciclati e packaging eco.",
		specs: "USB, 3 pulsanti, DPI 1200",
		price: 19,
		stock_quantity: 50,
		image_url: "mouse-5.jpg",
		category_id: 7,
	},
	{
		name: "TitanClick G7",
		brand: "IronWare",
		description:
			"Mouse da competizione con switch meccanici e polling rate 1000Hz.",
		specs: "USB-C, DPI 20.000, LED RGB",
		price: 79,
		stock_quantity: 12,
		image_url: "mouse-6.jpg",
		category_id: 7,
	},
	{
		name: "BlitzMouse Z1",
		brand: "BlitzGear",
		description: "Mouse compatto per gamer in mobilità.",
		specs: "Wireless 2.4GHz, DPI 10.000, batteria ricaricabile",
		price: 59,
		stock_quantity: 22,
		image_url: "mouse-7.jpg",
		category_id: 7,
	},
	{
		name: "HyperMouse Edge",
		brand: "HyperZone",
		description: "Mouse RGB con profili personalizzabili e memoria onboard.",
		specs: "USB, DPI 16.000, 9 pulsanti",
		price: 64,
		stock_quantity: 16,
		image_url: "mouse-8.jpg",
		category_id: 7,
	},
	{
		name: "OmegaTrack Prime",
		brand: "OmegaPlay",
		description: "Mouse con tracciamento laser e design premium.",
		specs: "USB-C, DPI 24.000, corpo in alluminio",
		price: 99,
		stock_quantity: 10,
		image_url: "mouse-9.jpg",
		category_id: 7,
	},
	{
		name: "CityMouse Urban",
		brand: "CityTech",
		description: "Mouse wireless compatto per uso quotidiano e portabilità.",
		specs: "Bluetooth, DPI 1600, batteria 30 giorni",
		price: 29,
		stock_quantity: 45,
		image_url: "mouse-10.jpg",
		category_id: 7,
	},
	{
		name: "Logitech G915 TKL",
		brand: "Logitech",
		description:
			"Tastiera meccanica wireless con switch a basso profilo e RGB Lightsync.",
		specs: "Switch GL Tactile, connessione LIGHTSPEED, layout TKL",
		price: 229,
		stock_quantity: 25,
		image_url: "keyboard-1.jpg",
		category_id: 8,
	},
	{
		name: "Razer Huntsman V2",
		brand: "Razer",
		description:
			"Tastiera con switch ottici Razer per una risposta ultrarapida.",
		specs:
			"Switch ottici lineari, polling rate 8000Hz, retroilluminazione Chroma RGB",
		price: 199,
		stock_quantity: 30,
		image_url: "keyboard-2.jpg",
		category_id: 8,
	},
	{
		name: "Corsair K95 RGB Platinum XT",
		brand: "Corsair",
		description: "Tastiera meccanica premium con macro dedicate e poggiapolsi.",
		specs: "Switch Cherry MX Brown, 6 tasti macro, retroilluminazione RGB",
		price: 229,
		stock_quantity: 18,
		image_url: "keyboard-3.jpg",
		category_id: 8,
	},
	{
		name: "SteelSeries Apex Pro",
		brand: "SteelSeries",
		description:
			"Tastiera con switch OmniPoint regolabili per attuazione personalizzata.",
		specs: "Display OLED integrato, alluminio aeronautico, RGB dinamico",
		price: 219,
		stock_quantity: 22,
		image_url: "keyboard-4.jpg",
		category_id: 8,
	},
	{
		name: "HyperX Alloy Origins",
		brand: "HyperX",
		description: "Tastiera compatta e resistente con switch HyperX meccanici.",
		specs: "Switch HyperX Red, struttura in alluminio, layout compatto",
		price: 119,
		stock_quantity: 40,
		image_url: "keyboard-5.jpg",
		category_id: 8,
	},
	{
		name: "Cooler Master CK552",
		brand: "Cooler Master",
		description:
			"Tastiera meccanica RGB con switch Gateron e software dedicato.",
		specs: "Switch Gateron Red, anti-ghosting, full RGB",
		price: 99,
		stock_quantity: 35,
		image_url: "keyboard-6.jpg",
		category_id: 8,
	},
	{
		name: "Ducky One 3 Mini",
		brand: "Ducky",
		description:
			"Tastiera 60% famosa per la qualità costruttiva e i keycap PBT.",
		specs: "Switch Cherry MX Red, formato 60%, keycaps Double-shot PBT",
		price: 139,
		stock_quantity: 28,
		image_url: "keyboard-7.jpg",
		category_id: 8,
	},
	{
		name: "Asus ROG Strix Scope RX",
		brand: "Asus",
		description: "Tastiera da gaming con switch ottici RX e resistenza IP56.",
		specs: "Switch RX Red ottici, anti-ghosting, costruzione in alluminio",
		price: 159,
		stock_quantity: 20,
		image_url: "keyboard-8.jpg",
		category_id: 8,
	},
	{
		name: "Glorious GMMK Pro",
		brand: "Glorious",
		description: "Tastiera custom hot-swappable per personalizzazioni estreme.",
		specs: "Layout 75%, gasket mounted, RGB per-key, hot-swap",
		price: 169,
		stock_quantity: 15,
		image_url: "keyboard-9.jpg",
		category_id: 8,
	},
	{
		name: "Keychron K2 V2",
		brand: "Keychron",
		description: "Tastiera meccanica wireless compatibile con Mac e Windows.",
		specs: "Switch Gateron, Bluetooth 5.1, batteria 4000mAh",
		price: 89,
		stock_quantity: 45,
		image_url: "keyboard-10.jpg",
		category_id: 8,
	},
	{
		name: "Samsung Odyssey G9",
		brand: "Samsung",
		description: "Monitor ultrawide curvo da 49'' con refresh rate a 240Hz.",
		specs: "49'' QLED, 5120x1440, 240Hz, 1ms, HDR1000",
		price: 1499,
		stock_quantity: 12,
		image_url: "monitor-1.jpg",
		category_id: 9,
	},
	{
		name: "LG UltraGear 27GP950",
		brand: "LG",
		description: "Monitor 4K da 27'' con tecnologia Nano IPS e 144Hz.",
		specs: "27'' Nano IPS, 3840x2160, 144Hz, 1ms, HDR600",
		price: 899,
		stock_quantity: 20,
		image_url: "monitor-2.jpg",
		category_id: 9,
	},
	{
		name: "ASUS ROG Swift PG259QN",
		brand: "ASUS",
		description: "Monitor eSports da 24.5'' con refresh rate a 360Hz.",
		specs: "24.5'' IPS, 1920x1080, 360Hz, 1ms, G-Sync",
		price: 699,
		stock_quantity: 25,
		image_url: "monitor-3.jpg",
		category_id: 9,
	},
	{
		name: "Acer Predator X34 GS",
		brand: "Acer",
		description: "Monitor curvo ultrawide da 34'' con supporto G-Sync.",
		specs: "34'' IPS curvo, 3440x1440, 180Hz, HDR400",
		price: 999,
		stock_quantity: 18,
		image_url: "monitor-4.jpg",
		category_id: 9,
	},
	{
		name: "Gigabyte M32U",
		brand: "Gigabyte",
		description: "Monitor gaming 4K da 32'' con HDMI 2.1 per console next-gen.",
		specs: "32'' IPS, 3840x2160, 144Hz, 1ms, HDMI 2.1",
		price: 749,
		stock_quantity: 22,
		image_url: "monitor-5.jpg",
		category_id: 9,
	},
	{
		name: "MSI Optix MAG274QRF-QD",
		brand: "MSI",
		description: "Monitor QHD con pannello Rapid IPS e Quantum Dot.",
		specs: "27'' QHD, 2560x1440, 165Hz, 1ms, HDR",
		price: 449,
		stock_quantity: 30,
		image_url: "monitor-6.jpg",
		category_id: 9,
	},
	{
		name: "Dell Alienware AW3423DW",
		brand: "Alienware",
		description: "Monitor QD-OLED curvo da 34'' con contrasto infinito.",
		specs: "34'' QD-OLED, 3440x1440, 175Hz, HDR TrueBlack 400",
		price: 1299,
		stock_quantity: 14,
		image_url: "monitor-7.jpg",
		category_id: 9,
	},
	{
		name: "BenQ EX3415R",
		brand: "BenQ",
		description: "Monitor curvo ultrawide per gaming immersivo.",
		specs: "34'' IPS curvo, 3440x1440, 144Hz, HDR400",
		price: 849,
		stock_quantity: 16,
		image_url: "monitor-8.jpg",
		category_id: 9,
	},
	{
		name: "AOC 24G2U",
		brand: "AOC",
		description: "Monitor Full HD 24'' entry-level con 144Hz.",
		specs: "24'' IPS, 1920x1080, 144Hz, 1ms, FreeSync",
		price: 199,
		stock_quantity: 40,
		image_url: "monitor-9.jpg",
		category_id: 9,
	},
	{
		name: "ViewSonic Elite XG270Q",
		brand: "ViewSonic",
		description: "Monitor QHD da 27'' con colori vividi e refresh rate 165Hz.",
		specs: "27'' IPS, 2560x1440, 165Hz, HDR400",
		price: 429,
		stock_quantity: 26,
		image_url: "monitor-10.jpg",
		category_id: 9,
	},
	{
		name: "TitanShell X5",
		brand: "IronWare",
		description:
			"Case ATX con pannello laterale in vetro temperato e flusso d’aria ottimizzato.",
		specs: "Mid Tower, 4 ventole incluse, supporto GPU fino a 400mm",
		price: 129,
		stock_quantity: 20,
		image_url: "case-1.jpg",
		category_id: 10,
	},
	{
		name: "StealthBox S1",
		brand: "StealthTech",
		description: "Case minimal nero opaco con isolamento acustico.",
		specs: "Micro ATX, pannelli fonoassorbenti, USB-C frontale",
		price: 99,
		stock_quantity: 25,
		image_url: "case-2.jpg",
		category_id: 10,
	},
	{
		name: "NovaFrame RGB",
		brand: "NovaTech",
		description:
			"Case con illuminazione RGB integrata e supporto raffreddamento liquido.",
		specs: "ATX, 3 ventole RGB, radiatore 360mm",
		price: 149,
		stock_quantity: 15,
		image_url: "case-3.jpg",
		category_id: 10,
	},
	{
		name: "EcoShell Lite",
		brand: "GreenByte",
		description:
			"Case eco-friendly con materiali riciclati e packaging sostenibile.",
		specs: "Mini Tower, airflow passivo, compatibile con SSD M.2",
		price: 69,
		stock_quantity: 30,
		image_url: "case-4.jpg",
		category_id: 10,
	},
	{
		name: "BlitzTower G7",
		brand: "BlitzGear",
		description: "Case da gaming con struttura rinforzata e LED dinamici.",
		specs: "Full Tower, supporto GPU verticale, 5 ventole incluse",
		price: 179,
		stock_quantity: 10,
		image_url: "case-5.jpg",
		category_id: 10,
	},
	{
		name: "HyperCase Z1",
		brand: "HyperZone",
		description: "Case compatto per build ITX ad alte prestazioni.",
		specs: "Mini ITX, alluminio spazzolato, gestione cavi ottimizzata",
		price: 109,
		stock_quantity: 18,
		image_url: "case-6.jpg",
		category_id: 10,
	},
	{
		name: "OmegaVault Prime",
		brand: "OmegaPlay",
		description:
			"Case premium con doppia camera e supporto radiatori multipli.",
		specs: "ATX, doppio compartimento, pannello in vetro fumé",
		price: 199,
		stock_quantity: 8,
		image_url: "case-7.jpg",
		category_id: 10,
	},
	{
		name: "VortexShell V3",
		brand: "VortexLab",
		description:
			"Case modulare per configurazioni personalizzate e upgrade rapidi.",
		specs: "Mid Tower, pannelli removibili, supporto fino a 9 ventole",
		price: 139,
		stock_quantity: 12,
		image_url: "case-8.jpg",
		category_id: 10,
	},
	{
		name: "CityCase Urban",
		brand: "CityTech",
		description: "Case elegante per ambienti professionali e home office.",
		specs: "ATX, design compatto, porte USB 3.2 frontali",
		price: 89,
		stock_quantity: 22,
		image_url: "case-9.jpg",
		category_id: 10,
	},
	{
		name: "ShadowCrate Elite",
		brand: "DarkCore",
		description:
			"Case da gioco con illuminazione interna e supporto GPU oversize.",
		specs: "Full Tower, vetro temperato, supporto GPU 420mm",
		price: 159,
		stock_quantity: 14,
		image_url: "case-10.jpg",
		category_id: 10,
	},
	{
		name: "Logitech G560",
		brand: "Logitech",
		description:
			"Speaker da gaming con illuminazione RGB Lightsync e subwoofer.",
		specs: "Potenza 240W, DTS:X Ultra, Bluetooth + Jack 3.5mm + USB",
		price: 199,
		stock_quantity: 25,
		image_url: "speaker-1.jpg",
		category_id: 11,
	},
	{
		name: "Razer Nommo Pro",
		brand: "Razer",
		description:
			"Coppia di speaker premium THX certificati con subwoofer dedicato.",
		specs: "THX, Dolby Virtual Surround, connessione USB + Bluetooth",
		price: 499,
		stock_quantity: 12,
		image_url: "speaker-2.jpg",
		category_id: 11,
	},
	{
		name: "Creative Pebble Pro",
		brand: "Creative",
		description: "Speaker compatti con illuminazione RGB e audio potenziato.",
		specs: "Potenza 20W RMS, USB-C, Jack 3.5mm, Bluetooth 5.3",
		price: 79,
		stock_quantity: 40,
		image_url: "speaker-3.jpg",
		category_id: 11,
	},
	{
		name: "Edifier G2000",
		brand: "Edifier",
		description: "Speaker da gaming con design compatto e illuminazione RGB.",
		specs: "Potenza 32W, Bluetooth 5.0, USB + AUX",
		price: 109,
		stock_quantity: 30,
		image_url: "speaker-4.jpg",
		category_id: 11,
	},
	{
		name: "SteelSeries Arena 7",
		brand: "SteelSeries",
		description: "Sistema 2.1 con subwoofer e illuminazione RGB ambientale.",
		specs: "Potenza 100W, Bluetooth, USB + Jack 3.5mm",
		price: 329,
		stock_quantity: 18,
		image_url: "speaker-5.jpg",
		category_id: 11,
	},
	{
		name: "Bose Companion 2 Series III",
		brand: "Bose",
		description: "Speaker multimediali con suono bilanciato e design compatto.",
		specs: "Potenza 22W, Jack 3.5mm doppio ingresso, controllo volume",
		price: 129,
		stock_quantity: 28,
		image_url: "speaker-6.jpg",
		category_id: 11,
	},
	{
		name: "Harman Kardon SoundSticks 4",
		brand: "Harman Kardon",
		description: "Iconico sistema 2.1 con design trasparente e audio potente.",
		specs: "Potenza 140W, Bluetooth, subwoofer dedicato",
		price: 299,
		stock_quantity: 14,
		image_url: "speaker-7.jpg",
		category_id: 11,
	},
	{
		name: "JBL Quantum Duo",
		brand: "JBL",
		description:
			"Speaker da gaming con effetti luce sincronizzati e bassi potenti.",
		specs: "Potenza 20W RMS, Bluetooth + Jack 3.5mm, RGB",
		price: 159,
		stock_quantity: 22,
		image_url: "speaker-8.jpg",
		category_id: 11,
	},
	{
		name: "Klipsch ProMedia 2.1",
		brand: "Klipsch",
		description:
			"Sistema 2.1 con subwoofer, bassi profondi e audio cristallino.",
		specs: "Potenza 200W, THX Certified, Jack 3.5mm",
		price: 299,
		stock_quantity: 16,
		image_url: "speaker-9.jpg",
		category_id: 11,
	},
	{
		name: "Trust GXT 658 Tytan",
		brand: "Trust",
		description: "Sistema 5.1 entry-level con illuminazione LED.",
		specs: "Potenza 180W, telecomando wireless, jack 3.5mm",
		price: 149,
		stock_quantity: 35,
		image_url: "speaker-10.jpg",
		category_id: 11,
	},
];

module.exports = products;
